language: c

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libzip-dev

before install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install curl; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libzip; fi

script:
    - cd src
    - make

