addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libzip-dev

language: c
compiler:
    - clang
    - gcc

script: cd src && make
install: true

os:
    - linux
    - osx
sudo: false
